# Generated by Django 5.2.6 on 2025-09-29 09:53

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompetitiveAnalysis',
            fields=[
            ],
            options={
                'verbose_name': 'Competitive Analysis',
                'verbose_name_plural': 'Competitive Analyses',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('api.analysis',),
        ),
        migrations.CreateModel(
            name='HighLevelAnalysis',
            fields=[
            ],
            options={
                'verbose_name': 'High-Level Analysis',
                'verbose_name_plural': 'High-Level Analyses',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('api.analysis',),
        ),
        migrations.CreateModel(
            name='KeyIndividualsAnalysis',
            fields=[
            ],
            options={
                'verbose_name': 'Key Individuals Analysis',
                'verbose_name_plural': 'Key Individuals Analyses',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('api.analysis',),
        ),
        migrations.CreateModel(
            name='MarketAnalysis',
            fields=[
            ],
            options={
                'verbose_name': 'Market Analysis',
                'verbose_name_plural': 'Market Analyses',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('api.analysis',),
        ),
        migrations.CreateModel(
            name='PerceptionAnalysis',
            fields=[
            ],
            options={
                'verbose_name': 'Perception Analysis',
                'verbose_name_plural': 'Perception Analyses',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('api.analysis',),
        ),
        migrations.CreateModel(
            name='IndividualRisk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='individual_risks', to='api.analysis')),
            ],
        ),
        migrations.CreateModel(
            name='KeyIndividual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_board_member', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=255)),
                ('role', models.CharField(blank=True, max_length=255)),
                ('experience', models.CharField(blank=True, max_length=255)),
                ('education', models.CharField(blank=True, max_length=255)),
                ('credibility_score', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('public_perception', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('previous_companies', models.JSONField(blank=True, default=list)),
                ('strengths', models.JSONField(blank=True, default=list)),
                ('achievements', models.JSONField(blank=True, default=list)),
                ('social_media', models.JSONField(blank=True, default=dict)),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='individuals', to='api.analysis')),
            ],
        ),
        migrations.CreateModel(
            name='PublicMention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('person', models.CharField(blank=True, max_length=255)),
                ('source', models.CharField(blank=True, max_length=255)),
                ('date', models.DateField(blank=True, null=True)),
                ('summary', models.TextField(blank=True)),
                ('sentiment', models.CharField(blank=True, max_length=50)),
                ('url', models.URLField(blank=True)),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='public_mentions', to='api.analysis')),
            ],
        ),
    ]
