# Generated by Django 5.2.6 on 2025-09-30 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_delete_competitiveanalysis_delete_highlevelanalysis_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='keyindividualsanalysis',
            name='team_strengths',
            field=models.JSONField(default=list, help_text='Team strengths and positive attributes'),
        ),
    ]
