# Generated by Django 5.2.6 on 2025-09-30 05:16

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_competitiveanalysis_benchmarks_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Competitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Competitor company name', max_length=255)),
                ('position', models.CharField(blank=True, help_text='Market position description', max_length=255)),
                ('logo', models.CharField(default='📊', help_text='Emoji or icon representation', max_length=10)),
                ('employees', models.CharField(blank=True, help_text="Number of employees (e.g., '100-500')", max_length=100)),
                ('headquarters', models.CharField(blank=True, help_text='Headquarters location', max_length=255)),
                ('founded', models.CharField(blank=True, help_text='Year founded', max_length=50)),
                ('funding', models.CharField(blank=True, help_text="Funding amount (e.g., '$50M')", max_length=100)),
                ('market_share', models.CharField(blank=True, help_text='Market share percentage', max_length=50)),
                ('revenue', models.CharField(blank=True, help_text="Revenue (e.g., '$10M ARR')", max_length=100)),
                ('score', models.IntegerField(default=0, help_text='Overall competitive score (0-100)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('trend', models.CharField(choices=[('up', 'Trending Up'), ('down', 'Trending Down'), ('stable', 'Stable')], default='stable', help_text='Market trend', max_length=10)),
                ('strengths', models.JSONField(default=list, help_text='List of competitor strengths')),
                ('weaknesses', models.JSONField(default=list, help_text='List of competitor weaknesses')),
                ('display_order', models.IntegerField(default=0, help_text='Order in which to display competitors')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competitors', to='api.competitiveanalysis')),
            ],
            options={
                'verbose_name': 'Competitor',
                'verbose_name_plural': 'Competitors',
                'ordering': ['display_order', '-score', 'name'],
            },
        ),
    ]
