# Generated by Django 5.2.6 on 2025-09-30 05:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_competitor'),
    ]

    operations = [
        migrations.CreateModel(
            name='StrategicRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(help_text="Strategic category (e.g., 'Market Expansion', 'Product Development')", max_length=255)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', help_text='Priority level', max_length=20)),
                ('recommendations', models.JSONField(default=list, help_text='List of specific recommendations for this category')),
                ('description', models.TextField(blank=True, help_text='Optional description of the strategic area')),
                ('display_order', models.IntegerField(default=0, help_text='Order in which to display recommendations')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strategic_recommendation_items', to='api.competitiveanalysis')),
            ],
            options={
                'verbose_name': 'Strategic Recommendation',
                'verbose_name_plural': 'Strategic Recommendations',
                'ordering': ['display_order', '-priority', 'category'],
            },
        ),
    ]
