# Generated by Django 5.2.6 on 2025-09-30 06:48

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_strategicrecommendation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perceptionanalysis',
            name='media_coverage',
        ),
        migrations.AddField(
            model_name='perceptionanalysis',
            name='risk_factors',
            field=models.JSONField(blank=True, default=list, help_text='DEPRECATED: Use structured models instead. Array of risk alerts'),
        ),
        migrations.AlterField(
            model_name='perceptionanalysis',
            name='brand_perception',
            field=models.JSONField(blank=True, default=list, help_text='DEPRECATED: Use structured models instead. Array of brand metrics'),
        ),
        migrations.AlterField(
            model_name='perceptionanalysis',
            name='social_sentiment',
            field=models.JSONField(blank=True, default=list, help_text='DEPRECATED: Use structured models instead. Array of key topics with sentiment'),
        ),
        migrations.CreateModel(
            name='CompetitorSentiment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(help_text='Competitor company name', max_length=255)),
                ('positive_percentage', models.IntegerField(help_text='Percentage of mentions that are positive (0-100)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('mentions_count', models.IntegerField(help_text='Total number of mentions', validators=[django.core.validators.MinValueValidator(0)])),
                ('is_current_company', models.BooleanField(default=False, help_text='Is this the company being analyzed (for highlighting)')),
                ('display_order', models.IntegerField(default=0, help_text='Order in which to display competitors')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competitor_sentiments', to='api.perceptionanalysis')),
            ],
            options={
                'verbose_name': 'Competitor Sentiment',
                'verbose_name_plural': 'Competitor Sentiments',
                'ordering': ['display_order', '-positive_percentage', 'company_name'],
            },
        ),
        migrations.CreateModel(
            name='SentimentBySource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_name', models.CharField(help_text="Source name (e.g., 'News Media', 'Social Media')", max_length=255)),
                ('positive_percentage', models.IntegerField(help_text='Percentage of mentions that are positive (0-100)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('mentions_count', models.IntegerField(help_text='Total number of mentions from this source', validators=[django.core.validators.MinValueValidator(0)])),
                ('sentiment_label', models.CharField(blank=True, help_text="Human-readable sentiment label (e.g., 'Positive', 'Neutral-Positive')", max_length=50)),
                ('change_vs_previous', models.CharField(blank=True, help_text="Change indicator (e.g., '+12% vs last month')", max_length=50)),
                ('display_order', models.IntegerField(default=0, help_text='Order in which to display sources')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sentiment_sources', to='api.perceptionanalysis')),
            ],
            options={
                'verbose_name': 'Sentiment by Source',
                'verbose_name_plural': 'Sentiment by Sources',
                'ordering': ['display_order', '-positive_percentage', 'source_name'],
            },
        ),
    ]
