# Generated by Django 5.2.6 on 2025-09-30 06:55

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_perceptionanalysis_media_coverage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecentMention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the article/mention', max_length=500)),
                ('source', models.CharField(help_text="Source (e.g., 'TechCrunch', 'LinkedIn', 'Twitter')", max_length=255)),
                ('date', models.DateField(help_text='Publication date')),
                ('url', models.URLField(blank=True, help_text='Link to the original article/post')),
                ('excerpt', models.TextField(help_text='Brief excerpt or summary of the mention')),
                ('reach', models.CharField(blank=True, help_text="Reach metric (e.g., '2.3M', '156K')", max_length=50)),
                ('engagement_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('very_high', 'Very High')], default='medium', help_text='Engagement level', max_length=20)),
                ('sentiment_label', models.CharField(help_text="Sentiment label (e.g., 'Positive', 'Very Positive', 'Neutral-Positive')", max_length=50)),
                ('sentiment_score', models.IntegerField(help_text='Sentiment score (0-100)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('display_order', models.IntegerField(default=0, help_text='Order in which to display mentions')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recent_mentions', to='api.perceptionanalysis')),
            ],
            options={
                'verbose_name': 'Recent Mention',
                'verbose_name_plural': 'Recent Mentions',
                'ordering': ['display_order', '-date', '-sentiment_score'],
            },
        ),
    ]
