# Generated by Django 5.2.6 on 2025-09-30 07:05

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_recentmention'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeyTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_name', models.CharField(help_text="Topic name (e.g., 'Innovation', 'Leadership', 'Product Quality')", max_length=255)),
                ('sentiment_score', models.IntegerField(help_text='Sentiment score for this topic (0-100)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('mentions_count', models.IntegerField(help_text='Number of mentions for this topic', validators=[django.core.validators.MinValueValidator(0)])),
                ('trend', models.CharField(choices=[('up', 'Trending Up'), ('down', 'Trending Down'), ('stable', 'Stable')], default='stable', help_text='Trend direction', max_length=10)),
                ('description', models.TextField(blank=True, help_text='Optional description or context about this topic')),
                ('display_order', models.IntegerField(default=0, help_text='Order in which to display topics')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='key_topics', to='api.perceptionanalysis')),
            ],
            options={
                'verbose_name': 'Key Topic',
                'verbose_name_plural': 'Key Topics',
                'ordering': ['display_order', '-sentiment_score', 'topic_name'],
            },
        ),
    ]
