# Generated by Django 5.2.6 on 2025-09-30 07:10

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_keytopic'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_name', models.CharField(help_text="Metric name (e.g., 'Brand Awareness', 'Brand Trust', 'Innovation Perception')", max_length=255)),
                ('current_score', models.IntegerField(help_text='Current score for this metric (0-100)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('industry_benchmark', models.IntegerField(help_text='Industry benchmark score (0-100)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('trend', models.CharField(choices=[('up', 'Trending Up'), ('down', 'Trending Down'), ('stable', 'Stable')], default='stable', help_text='Trend direction over time', max_length=10)),
                ('description', models.TextField(blank=True, help_text='Optional description or context about this metric')),
                ('display_order', models.IntegerField(default=0, help_text='Order in which to display metrics')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brand_metrics', to='api.perceptionanalysis')),
            ],
            options={
                'verbose_name': 'Brand Metric',
                'verbose_name_plural': 'Brand Metrics',
                'ordering': ['display_order', '-current_score', 'metric_name'],
            },
        ),
    ]
