# Generated by Django 5.2.6 on 2025-09-30 07:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_brandmetric'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiskAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Risk alert title', max_length=500)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', help_text='Risk priority level', max_length=20)),
                ('description', models.TextField(help_text='Detailed description of the risk')),
                ('impact', models.TextField(blank=True, help_text='Potential impact if not addressed')),
                ('recommendation', models.TextField(blank=True, help_text='Recommended actions to mitigate the risk')),
                ('display_order', models.IntegerField(default=0, help_text='Order in which to display risk alerts')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_alerts', to='api.perceptionanalysis')),
            ],
            options={
                'verbose_name': 'Risk Alert',
                'verbose_name_plural': 'Risk Alerts',
                'ordering': ['display_order', '-priority', 'title'],
            },
        ),
    ]
