# Generated by Django 5.2.6 on 2025-09-30 07:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_riskalert'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketanalysis',
            name='barriers_to_entry',
            field=models.JSONField(blank=True, default=list, help_text='DEPRECATED: Use structured models instead. Barriers to market entry'),
        ),
        migrations.AlterField(
            model_name='marketanalysis',
            name='competitive_landscape',
            field=models.JSONField(blank=True, default=list, help_text='DEPRECATED: Use structured models instead. Competitive landscape analysis'),
        ),
        migrations.AlterField(
            model_name='marketanalysis',
            name='market_trends',
            field=models.JSONField(blank=True, default=list, help_text='DEPRECATED: Use structured models instead. Current market trends'),
        ),
        migrations.CreateModel(
            name='RevenueInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title describing the revenue information', max_length=500)),
                ('source', models.CharField(help_text="Source (e.g., 'Annual Report', 'TechCrunch', 'Investor Deck')", max_length=255)),
                ('date', models.DateField(help_text='Date of publication or report')),
                ('url', models.URLField(blank=True, help_text='Link to the original source')),
                ('revenue_figure', models.CharField(help_text="Revenue figure (e.g., '$10M ARR', '$50M Series A')", max_length=100)),
                ('description', models.TextField(help_text='Details and context about this revenue information')),
                ('reliability', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('verified', 'Verified')], default='medium', help_text='Reliability/confidence level of this information', max_length=20)),
                ('growth_rate', models.CharField(blank=True, help_text="Growth rate if mentioned (e.g., '+125% YoY')", max_length=50)),
                ('display_order', models.IntegerField(default=0, help_text='Order in which to display revenue items')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revenue_information', to='api.marketanalysis')),
            ],
            options={
                'verbose_name': 'Revenue Information',
                'verbose_name_plural': 'Revenue Information',
                'ordering': ['display_order', '-date'],
            },
        ),
    ]
