# Generated by Django 5.2.6 on 2025-09-30 07:53

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_marketanalysis_barriers_to_entry_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketanalysis',
            name='revenue_note',
            field=models.TextField(blank=True, help_text='Notes/caveats about revenue figures (e.g., year range, estimates)'),
        ),
        migrations.CreateModel(
            name='IndustryTrend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Trend title', max_length=255)),
                ('impact', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10)),
                ('relevance', models.IntegerField(help_text='Relevance score (0-100)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('description', models.TextField(blank=True)),
                ('display_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='industry_trends_items', to='api.marketanalysis')),
            ],
            options={
                'verbose_name': 'Industry Trend',
                'verbose_name_plural': 'Industry Trends',
                'ordering': ['display_order', '-relevance', 'title'],
            },
        ),
        migrations.CreateModel(
            name='MarketForce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('force_name', models.CharField(help_text="Force name (e.g., 'Competitive Rivalry')", max_length=255)),
                ('intensity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10)),
                ('score', models.IntegerField(help_text='Force intensity score (0-100)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('description', models.TextField(blank=True, help_text='Summary of the force dynamics')),
                ('factors', models.JSONField(default=list, help_text='Key factors list')),
                ('display_order', models.IntegerField(default=0, help_text='Order in which to display market forces')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='market_forces', to='api.marketanalysis')),
            ],
            options={
                'verbose_name': 'Market Force',
                'verbose_name_plural': 'Market Forces',
                'ordering': ['display_order', '-score', 'force_name'],
            },
        ),
        migrations.CreateModel(
            name='SalesChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_name', models.CharField(help_text='Platform or channel name (e.g., App Store, Direct Sales)', max_length=255)),
                ('url', models.URLField(blank=True)),
                ('installs_count', models.CharField(blank=True, help_text="Installs or customer count (e.g., '120K')", max_length=50)),
                ('revenue_amount', models.CharField(blank=True, help_text='Revenue amount for the channel', max_length=50)),
                ('rating', models.FloatField(blank=True, null=True)),
                ('reviews_count', models.IntegerField(blank=True, null=True)),
                ('change_percentage', models.FloatField(blank=True, null=True)),
                ('display_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_channels', to='api.marketanalysis')),
            ],
            options={
                'verbose_name': 'Sales Channel',
                'verbose_name_plural': 'Sales Channels',
                'ordering': ['display_order', '-updated_at', 'platform_name'],
            },
        ),
    ]
