# Generated by Django 5.2.6 on 2025-09-30 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_marketanalysis_revenue_note_industrytrend_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleschannel',
            name='count_unit',
            field=models.CharField(blank=True, help_text="Unit for count metric (e.g., 'Installs', 'Transactions', 'Products')", max_length=50),
        ),
        migrations.AlterField(
            model_name='saleschannel',
            name='installs_count',
            field=models.CharField(blank=True, help_text="Primary count for this channel (e.g., '120K')", max_length=50),
        ),
    ]
